services:
  filebrowser:
    container_name: filebrowser
    image: 'filebrowser/filebrowser:${FILEBROWSER_TAG:-latest}'
    restart: always
    ports:
      - ${FILEBROWSER_PORT:-88}:80/tcp
    volumes:
      - ${FILEBROWSER_SRV_PATH}:/srv
      - ${FILEBROWSER_DB_FILE:-}:/database.db
      - ${FILEBROWSER_CONFIG_FILE-}:/filebrowser.json


